### Get all members
GET http://localhost:3000/members

### Get member with specific id
GET http://localhost:3000/members/1

### Add member
POST http://localhost:3000/members
Content-Type: application/json

{
  "first_name": "Dongyoung",
  "last_name": "Lim"
}

### Update member with specific id
PUT hptt://localhost:3000/members/0
